### ISSUE TITLE
create a bower package

### ISSUE THREAD

**Issue by anshupitlia** [Wildhoney/EmberRickshaw#19]

**Comment by Wildhoney** [comment]
Sorry :+1: Available in Bower as `ember-rickshaw`.

**Comment by anshupitlia** [comment]
Actually when I tried to install it yesterday using bower, bower install ember-rickshaw, it said no such package available in bower. So I added it here, It just works now. Apologies..

**Comment by Wildhoney** [comment]
Nope, you were right. I've just added it to Bower &ndash; it was only available via npm.

**Comment by anshupitlia** [comment]
oh, okay,  thanks man!
